development:
  adapter: mysql
  database: xploreu_development
  username: root
  password:

test:
  adapter: mysql
  database: xploreu_test
  username: root
  password:

production:
  adapter: mysql
  database: xploreu_production
  username: deploy
  password: tr4v3l
  host: localhost
